name: Main Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 17, 21, 25 ]
    permissions:
      contents: read
      packages: read
      pages: read

    steps:
    - name: Checkout Main Project
      uses: actions/checkout@v4
      with:
        path: main-project

    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Set up Gradle environment
      uses: gradle/actions/setup-gradle@v3

    - name: Build with Gradle
      working-directory: main-project
      run: ./gradlew
      env:
        PROJECT_WORKFLOW: 'main-pull-request-matrix'
